# Set it to true when we we only want to print logs locally.
# print-msg-local = true

[ptal]
report-name= "SQL Data & Service"

# Could also be set with the environment variable:
#   - GHSTATS_GITHUB_TOKEN
#   - GHSTATS_FEISHU_WEBHOOK_TOKEN
[ptal.access]
feishu-webhook-token = ""
github-token = ""

[[ptal.repos]]
name = "tidb"
pr-owner-repo = "pingcap/tidb"
allow-pkgs = [
  "ddl",
  "disttask",
  "owner",
  "dumpling",
  "br/pkg/lightning",
]

[[ptal.repos]]
name = "tiflow"
pr-owner-repo = "pingcap/tiflow"
allow-pkgs = [
  "dm",
]